[project]
name = "generics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "configparser>=7.2.0",
    "pandas>=2.3.1",
    "sqlalchemy>=2.0.43",
]
